### PR TITLE
Add a FrameMonitor to the utils

### PR DESCRIPTION
**Pull request by liamchzh**
Please see #413

### CODE REVIEW

**Comment by Gamenot** [comment]
Is this being used anywhere? It is hard to justify adding it in if it is not being used, even if it is just in some test.

Also there is a similar utility in `smarts/core/utils/logging.py`:

https://github.com/huawei-noah/SMARTS/blob/8881e07ad83aea83e1b02d98a1bf65d851a3e392/smarts/core/utils/logging.py#L29-L35

**Review by Gamenot — COMMENTED** [review]
A question

**Comment by liamchzh** [comment]
> Is this being used anywhere? It is hard to justify adding it in if it is not being used, even if it is just in some test.
> 
> Also there is a similar utility (although different in use) in `smarts/core/utils/logging.py` if you are looking for something to compare against:
> 
> https://github.com/huawei-noah/SMARTS/blob/8881e07ad83aea83e1b02d98a1bf65d851a3e392/smarts/core/utils/logging.py#L29-L35

1. The idea of `timeit` is exactly what' in my mind when I implemented the monitor.
2. For sure, I will add a test.

**Review by Gamenot — APPROVED** [review]

**Review by Gamenot — APPROVED** [review]

**Review by iman512003 — APPROVED** [review]

**Comment by liamchzh** [comment]
Per [discussion](https://github.com/huawei-noah/SMARTS/issues/413#issuecomment-763713756), close this PR.

**Pull request closed without merging**
