### PR TITLE
TargetPose Example/Road waypoints bug

### PR DESCRIPTION
**Pull request by Gamenot**
This is an example using TargetPose.

Previous commit shows waypoint bug: https://github.com/huawei-noah/SMARTS/commit/e6dfc2cfed882631e9423787603eff0b12b4fc81

### CODE REVIEW

**Comment by Gamenot** [comment]
@YuechengLiu I have added an example. The `TargetPose` action space works as intended. (the mentioned bug is related to something else)

**Comment by YuechengLiu** [comment]
Thanks for the help！

**Comment by SXKai** [comment]
Hi， @Gamenot. I have a question about this feature. If I want to control the vehicle to reach a target point with targetPose (x, y, heading，speed) in one step, how can I implement it? Do I need to set the targetPose (x, y, heading，speed)  into obs firstly, and then use .act() function to get the action?

**Comment by Gamenot** [comment]
Hello @SXKai, the description of the TargetPose is as follows:

* `position x` value in meters with +x facing right.
* `position y` value in meters with +y facing front.
* `heading` in radians with 0 facing north and counterclockwise rotation.
* `time horizon` in seconds as to when the vehicle should arrive at the given pose.

Provide the same value as the timestep of the simulation (generally 0.1) if you want the vehicle to arrive at the pose on the next step.

**Comment by SXKai** [comment]
Thanks for your help.

**Comment by YuechengLiu** [comment]
Hello @Gamenot . 

If the agent take a action `TargetPos` at step `t`, will the agent accurately reach the specified location at step `t+1`? Are there any dynamic constraints in this process？

**Comment by YuechengLiu** [comment]
Thanks @Gamenot , I just want to know how it works. 

So under the action space `TargetPos`, is this dynamics constraints realized by `pybullet` or `SMARTS`? Is this constraints same as the cases under action space `Imitation`?

**Comment by Gamenot** [comment]
@YuechengLiu From my understanding and from double-checking the `ActionSpaceType.TargetPose` related vehicle control, the physics related constraints are the exact same as are seen with `Imitation`/`Direct` and fall under `SMARTS` control.

If attempting to reach to a target trajectory using pure dynamics that would require something like Continuous, Lane, ActuatorDynamic, LaneWithContinuousSpeed, Trajectory, or MPC. Such as described https://github.com/huawei-noah/SMARTS/blob/develop/docs/sim/agent.rst#agentinterface.

**Pull request closed without merging**
