### PR TITLE
Bugtest SUMO Crashing on Turns

### PR DESCRIPTION
**Pull request by Gamenot**
This one seems to occur in just the second episode of loop. Replicate with just a call to `supervisord` and Eclipse SUMO sumo Version 1.8.0.

### CODE REVIEW

**Comment by Gamenot** [comment]
@Adaickalavan I found out one of the reasons why we could not reproduce the sumo crash on docker.

For some reason Docker is installing a different version of smarts in the image.

**Comment by Gamenot** [comment]
I have put up an image that should be able to reproduce the problem https://hub.docker.com/layers/huaweinoah/smarts/bugtest_0.4.13-sumo_1_8_0/images/sha256-51025124ec25309e923893c59c569939d788983fd76d7e5b3bac116d9c3dddcb?context=repo .

**Comment by Adaickalavan** [comment]
I ran the given commands on the docker image.

Test outcomes are as follows. Each test was started afresh by restarting the docker and re-running all commands.

| Test # | Outcome |
| :----: | ---- |
| 1 | Tracii connection error in 3rd episode |
| 2 | Finished all 10 episodes without any errors |
| 3 | Finished all 10 episodes without any errors |
| 4 | Finished all 10 episodes without any errors |

Perhaps, the docker image should be tested multiple number of times by more people @iman512003 @JingfeiPeng.

**Comment by Gamenot** [comment]
Going to try using #612 to get this to become fully reproducible.

**Comment by Gamenot** [comment]
#619 is looking at this issue more in depth.

**Pull request closed without merging**
