### PR TITLE
Speed up rllib test

### PR DESCRIPTION
**Pull request by Gamenot**
Shorten the time of the `test_rllib_hiway_env` test.

### CODE REVIEW

**Comment by saulfield** [comment]
What is the speed improvement for this? I think this test took around 30 mins on my machine originally.

**Comment by qianyi-sun** [comment]
Not sure if this is reasonable, how about we create a even simpler scenario or duplicate an existing scenario just for the test and maybe gitignore it to prevent possible accidentally removal of it? I just have a feeling that in the future somehow we might forget that we have set this scenario for the test and delete it for some reason..

**Comment by Gamenot** [comment]
> Not sure if this is reasonable, how about we create a even simpler scenario or duplicate an existing scenario just for the test and maybe gitignore it to prevent possible accidentally removal of it? I just have a feeling that in the future somehow we might forget that we have set this scenario for the test and delete it for some reason..

I do not think that is possible since it is linked to the CI.

**Comment by Gamenot** [comment]
> What is the speed improvement for this? I think this test took around 30 mins on my machine originally.

I had the test take 3 minutes with this version.

**Review by saulfield — APPROVED** [review]

**Comment by Gamenot** [comment]
@saulfield I think the next step after may be to limit the number of CPUs.

**Pull request merged**
