### PR TITLE
Move dataset converter tool

### PR DESCRIPTION
**Pull request by Adaickalavan**
Moved `traffic_histories_vehicle_replacement.py` from `examples` folder to `smarts/waymo/` folder as it is more of a tool to generate SMARTS compatible observations from offline datasets rather than an example.

### CODE REVIEW

**Review by qianyi-sun — APPROVED** [review]

**Comment by qianyi-sun** [comment]
I agree to move this script from examples to a tool but maybe we should re-consider to put it into `smarts/waymo` but to a more general, non-waymo folder since we also use it for converting NGSIM datasets too.

**Comment by Gamenot** [comment]
> I agree to move this script from examples to a tool but maybe we should re-consider to put it into `smarts/waymo` but to a more general, non-waymo folder since we also use it for converting NGSIM datasets too.

I think I agree on this point as well, I am not sure if this goes into something like `smarts/dataset_core`.

**Comment by Adaickalavan** [comment]
@qianyi-sun @Gamenot 
What about moving `traffic_histories_to_observations.py` into a new folder named `smarts/dataset`?

**Comment by Gamenot** [comment]
> @qianyi-sun @Gamenot What about moving `traffic_histories_to_observations.py` into a new folder named `smarts/dataset`?

That seems reasonable.

**Review by Gamenot — APPROVED** [review]

**Pull request merged**
