### PR TITLE
Run evaluation in parallel to training in ULTRA

### PR DESCRIPTION
**Pull request by christianjans**
Based off of #624.

## Concerns:
- Produces chaotic output:
```sh
(pid=11091) ╭────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────────────╮
(pid=11091) │            Episode │           Sim/Wall │        Total Steps │          Steps/Sec │              Score │
(pid=11091) ├────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────────────┤
│              47/50 │               3.29 │                 16 │              32.92 │       000: -0.9140 │
(pid=11091) │                0/1 │               7.14 │                  7 │              71.36 │       000: -1.4256 │
(pid=11091) ╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
(pid=11066) │                0/1 │               1.20 │                  7 │              12.01 │       000: -0.9187 │
(pid=11066) ╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
│              48/50 │               3.53 │                  8 │              35.33 │       000: -1.5018 │
│              49/50 │               1.79 │                 14 │              17.88 │       000: -1.9412 │
╰────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────────────╯
```
- Receives this error every time an evaluation finishes when running in non-headless mode. **This can be fixed by upgrading the SMARTS version to something like 0.4.15.**
```sh
(pid=11091) *** Aborted at 1616524104 (unix time) try "date -d @1616524104" if you are using GNU date ***
(pid=11091) PC: @                0x0 (unknown)
(pid=11091) *** SIGSEGV (@0x7f66e3ffec60) received by PID 11248 (TID 0x7f6944d79740) from PID 18446744073239784544; stack trace: ***
(pid=11091)     @     0x7f6944954980 (unknown)
(pid=11091)     @     0x7f69429f8afb pollset_shutdown()
(pid=11091)     @     0x7f69429d5188 cq_shutdown_next()
(pid=11091)     @     0x7f69429d559f grpc_completion_queue_shutdown
(pid=11091)     @     0x7f694258e91c ray::gcs::ServiceBasedGcsClient::~ServiceBasedGcsClient()
(pid=11091)     @     0x7f694258eb51 ray::gcs::ServiceBasedGcsClient::~ServiceBasedGcsClient()
(pid=11091)     @     0x7f694249627b ray::gcs::GlobalStateAccessor::~GlobalStateAccessor()
(pid=11091)     @     0x7f69423ff581 __pyx_tp_dealloc_3ray_7_raylet_GlobalStateAccessor()
(pid=11091)     @     0x55bb7d2cb764 (unknown)
(pid=11091)     @     0x55bb7d1d0320 _PyObjectDict_SetItem
(pid=11091)     @     0x55bb7d2ce7f1 _PyObject_GenericSetAttrWithDict
(pid=11091)     @     0x55bb7d1dda23 PyObject_SetAttr
(pid=11091)     @     0x55bb7d21e47f _PyEval_EvalFrameDefault
(pid=11091)     @     0x55bb7d1aee1a _PyFunction_FastCallKeywords
(pid=11091)     @     0x55bb7d21dfde _PyEval_EvalFrameDefault
(pid=11091)     @     0x55bb7d21ce2f _PyEval_EvalCodeWithName
(pid=11091)     @     0x55bb7d1aeefa _PyFunction_FastCallKeywords
(pid=11091)     @     0x55bb7d21dce6 _PyEval_EvalFrameDefault
(pid=11091)     @     0x55bb7d21ce2f _PyEval_EvalCodeWithName
(pid=11091)     @     0x55bb7d0edec0 _PyFunction_FastCallDict
(pid=11091)     @     0x55bb7d2892e2 PyErr_CheckSignals
(pid=11091)     @     0x55bb7d143a98 (unknown)
(pid=11091)     @     0x55bb7d3190c4 (unknown)
(pid=11091)     @     0x55bb7d1ad669 _PyMethodDef_RawFastCallKeywords
(pid=11091)     @     0x55bb7d1ad560 _PyCFunction_FastCallKeywords
(pid=11091)     @     0x55bb7d221d62 _PyEval_EvalFrameDefault
(pid=11091)     @     0x55bb7d21ce2f _PyEval_EvalCodeWithName
(pid=11091)     @     0x55bb7d1aeefa _PyFunction_FastCallKeywords
(pid=11091)     @     0x55bb7d21dfde _PyEval_EvalFrameDefault
(pid=11091)     @     0x55bb7d21ce2f _PyEval_EvalCodeWithName
(pid=11091)     @     0x55bb7d1aeefa _PyFunction_FastCallKeywords
(pid=11091)     @     0x55bb7d21dfde _PyEval_EvalFrameDefault
```
- Will potentially record data out of order if the `--eval-rate` flag value is too low and/or the `--max-episode-steps` is too high: https://github.com/huawei-noah/SMARTS/blob/a65215660f2b54d02d971dedf10ff56c7f3993cb/ultra/ultra/utils/episode.py#L253-L263 This should not be a problem if `--eval-rate` and `--max-episode-steps` are kept reasonable, i.e. not evaluating every episode (`--eval-rate` > 1) and keeping the max steps for the agent in an episode relatively low (`--max-episode-steps` <= 1200).
- Produces these errors at the end of the training session. **This can be fixed by upgrading the `grpcio==1.30.0` dependency of SMARTS to something like `grpcio==1.31.0` (see [this issue](https://github.com/grpc/grpc/issues/23290) from the GRPC repository).**
```sh
/usr/lib/python3.7/subprocess.py:883: ResourceWarning: subprocess 7946 is still running
  ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
Exception ignored in: <function _ChannelCallState.__del__ at 0x7f094c7bc5f0>
Traceback (most recent call last):
  File "/SMARTS/ultra/.venv/lib/python3.7/site-packages/grpc/_channel.py", line 1126, in __del__
AttributeError: 'NoneType' object has no attribute 'cancelled'
```

### CODE REVIEW

**Comment by AlexLewandowski** [comment]
> * Will potentially record data out of order if the `--eval-rate` flag value is too low: https://github.com/huawei-noah/SMARTS/blob/a65215660f2b54d02d971dedf10ff56c7f3993cb/ultra/ultra/utils/episode.py#L253-L263
>    This should not be a problem if `--eval-rate` is kept reasonable, i.e. not evaluating every episode (`--eval-rate` > 1).

This might be reason enough to log information to some format other than tensorboard.

**Comment by christianjans** [comment]
> This might be reason enough to log information to some format other than tensorboard.

True @AlexLewandowski. I believe the `all_data` attribute of episodes should contain all the data that has been gathered during training and testing for each agent: https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/ultra/ultra/utils/episode.py#L131 https://github.com/huawei-noah/SMARTS/blob/6cb8ffda74e235c25d63b74313623b2e03e402f7/ultra/ultra/utils/episode.py#L257-L275 Maybe this could help? I will investigate as well.

**Review by JenishPatel99 — APPROVED** [review]

**Review by AlexLewandowski — COMMENTED** [review]
Looks good, we should work on merging this with the changes in the ultra-eval-per-episode branch sometime tomorrow.

**Comment by christianjans** [comment]
> Looks good, we should work on merging this with the changes in the ultra-eval-per-episode branch sometime tomorrow.

Definitely! Sounds good.

**Comment by AlexLewandowski** [comment]
Whoops, I did this merge from the CLI which I did not know was possible. I think it's all set though, I was able to integrate the episode based evaluation and most of the generalization stuff. The one hiccup is gap_mode. I think this could be done by running the evaluation for eval_mode = True and eval_mode = False inside the for loop instead of two separate for loops. Then the task_ids can be bundled together, like: 

```
 evaluation_task_ids[(evaluation_task_id,evaluation_train_task_id)] = ...
```

I don't know if that would pose a problem though

**Comment by christianjans** [comment]
Oh okay no worries, we can maybe talk about it in today's meeting.

**Pull request merged**
