### PR TITLE
Remove `python-dev` dependency for smarts

### PR DESCRIPTION
**Pull request by qianyi-sun**
Remove `python-dev` dependency for lighter weight smarts
#1202

### CODE REVIEW

**Review by Gamenot — APPROVED** [review]
It looks like everything passes. This is a good win on dependency reduction.

**Review by Gamenot — CHANGES_REQUESTED** [review]
On second look there are a few other setup related files where python3.7-dev is installed.

**Comment by qianyi-sun** [comment]
> On second look there are a few other setup related files where python3.7-dev is installed.

By using `grep -d recurse 'python3.7-dev'`, python3.7-dev in all setup-related files are found and removed.

**Review by Gamenot — APPROVED** [review]
OK, it looks good now. Good work. :ship:

**Pull request merged**
