### PR TITLE
Update OpEn 0.1.193

### PR DESCRIPTION
**Pull request by Gamenot**

### CODE REVIEW

**Comment by JingfeiPeng** [comment]
should we remove some of the old wheel files?

**Comment by Gamenot** [comment]
> should we remove some of the old wheel files? (189 and 190)

Yes, we should remove the old ones, especially since they are up on PyPI.

**Comment by Gamenot** [comment]
Going back over this PR, I see it is better to just not have the open binaries in repository in the first place.

**Comment by JingfeiPeng** [comment]
Might be useful to provide the commands to build and install open-agent and solver under the readme here: https://github.com/huawei-noah/SMARTS/tree/master/zoo/policies/open-agent

**Pull request closed without merging**
