### PR TITLE
Move scenario construction

### PR DESCRIPTION
**Pull request by Adaickalavan**
+ Keep cli code lean and move scenario build code into smarts.
+ Avoids starting another subprocess during programmatic scenario builds.
+ Addresses https://github.com/huawei-noah/SMARTS/pull/1793#discussion_r1081503528

### CODE REVIEW

**Review by saulfield — APPROVED** [review]

**Comment by Gamenot** [comment]
I am not sure all instances of `build_scenario` have been updated. I think there is one in the competition entry-point and in the hiway_v1 example.

**Comment by Gamenot** [comment]
@Adaickalavan The following files still have `build_scenario` from sstudio.

- hiway_env_v1_lane_follower.py
- intersection_env.py
- driving_smarts_competition_env.py

**Comment by Adaickalavan** [comment]
> @Adaickalavan The following files still have `build_scenario` from `sstudio`.
> 
> * hiway_env_v1_lane_follower.py
> * intersection_env.py
> * driving_smarts_competition_env.py

oops ... I missed a few. I have changed them now.

**Comment by Gamenot** [comment]
There appears to be an issue relevant to `build_scenario`.

**Pull request merged**
