### PR TITLE
ULTRA Evaluate agent after grade completion

### PR DESCRIPTION
**Pull request by JenishPatel99**
Addressing Issue: #760

### CODE REVIEW

**Review by AlexLewandowski — APPROVED** [review]
I feel that something like this could be handled in the train script as well. Of course, we did discuss keeping the train script relatively "vanilla" and per that discussion, this seeems sensible.

**Review by christianjans — APPROVED** [review]
Looks good! 👍

I wonder if perhaps some of the logic can be simplified, but maybe that will become more apparent in the context of the entire grade-based pull request and also some of the new changes in the ultra-develop branch.

**Comment by JenishPatel99** [comment]
@AlexLewandowski I completely agree, there are some aspects from the grade-based stuff that can be added to the "vanilla" train later on. But for now, I will try to keep the same template as the vanilla train script, so the only difference would be no-gb and gb.

> I feel that something like this could be handled in the train script as well. Of course, we did discuss keeping the train script relatively "vanilla" and per that discussion, this seeems sensible.

**Comment by JenishPatel99** [comment]
@christianjans I have not explicit refactored the grade-based, but as I continue I will keep in mind of any simplification of the code. But yeah, once the dynamic scenario addition is done, we can start filtering the code

> Looks good! 👍
> 
> I wonder if perhaps some of the logic can be simplified, but maybe that will become more apparent in the context of the entire grade-based pull request and also some of the new changes in the ultra-develop branch.

**Pull request merged**
